#%RAML 1.0 DataType
type: object
properties:
  customerId?: number
  firstName?: string
  lastName?: string
  city?: string
  pin?: string
  state?: string
  registrationTime?: string
  address?: string